# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('filesys', models.CharField(max_length=120)),
                ('bench', models.CharField(max_length=120)),
                ('mx1', models.FloatField(blank=True)),
                ('mx2', models.FloatField(blank=True)),
                ('mx3', models.FloatField(blank=True)),
                ('mx4', models.FloatField(blank=True)),
                ('mx5', models.FloatField(blank=True)),
                ('mx6', models.FloatField(blank=True)),
                ('mx7', models.FloatField(blank=True)),
                ('mx8', models.FloatField(blank=True)),
            ],
        ),
    ]
