# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mat2web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrix',
            name='mx5',
        ),
        migrations.RemoveField(
            model_name='matrix',
            name='mx6',
        ),
        migrations.RemoveField(
            model_name='matrix',
            name='mx7',
        ),
        migrations.RemoveField(
            model_name='matrix',
            name='mx8',
        ),
    ]
